@startuml
title Sequence diagram Psec
autonumber
actor "Infsec engineer" as Foo
box "Mail Server"
participant "Network admin\nmailbox" as Foo1
participant "Psec\nmailbox" as Foo2
end box
participant "Psec Server" as Foo3
participant "Log Server" as Foo4
participant "Access Switch" as Foo5
actor "Sysadmin" as Foo6
Foo -> Foo1 : Message requesting\na new device connection
Foo1 -> Foo2 : Request message forwarding
loop Check for incoming messages (twice a minute)
    Foo3 <-[#red]> Foo2 : POP3
alt Message check
    Foo3 -> Foo3 : Creating a child process\nto execute one request
    note left
     Track ID contains
     the MAC address of the device
    end note
    Foo3 <-[#red]> Foo2 : SMTP
    Foo2 ->> Foo1 : Request accepted for processing
    note left
     "<<Device MAC address>>
     request accepted"
     in the message subject
    end note
    == Executing a single request ==
    loop Log server DB query (once per minute)
        Foo3 <-[#blue]> Foo4 : SSH connection to the log server,\nquery to the Syslog DB (netmiko)
        note left
         The request contains the MAC address
         of the new connected device
        end note
        hnote over Foo3, Foo4 : Waiting for device connection
        ...
        Foo6 -> Foo5 : Connecting a new device
        Foo5 ->> Foo4 : Syslog message
        note right
         Information security message
        end note
        Foo4 --> Foo3 : Response from log server DB
        Foo3 -> Foo3 : Syslog message parsing
        note left
         To configure the switch,
         you need the IP address
         and access port number
         to which the new device is connected.
        end note
        Foo3 <-[#blue]> Foo5 : SSH connection to the access switch,\nperforming configuration (netmiko)
        Foo3 <-[#red]> Foo2 : SMTP
        alt #LightBlue Execution result message
            Foo2 ->> Foo1 : Task completed
            note right
             Task execution status in the message subject,
             task execution log in the message body
            end note
        autonumber 14.1
        else #LightBlue Settings have been made before
            Foo2 ->> Foo1 : Task completed
        else #Pink Device in the excluded list
            Foo2 ->> Foo1 : Task failed
        else #Pink Connecting via hub
            Foo2 ->> Foo1 : Task failed
        else #Pink Access port in shutdown state
            Foo2 ->> Foo1 : Task failed
        else #Pink Failed to configure
            Foo2 ->> Foo1 : Task failed
        end
        autonumber 7.1
        break #Pink End of the working day (after 18:00)
            Foo2 ->> Foo1 : Task failed
            note right
             The device has not been connected during the day
            end note
        end
    end
autonumber 6.1
else #Pink The Request was not received from an Infsec engineer
    Foo2 ->> Foo1 : Request not accepted
else #Pink There is no MAC address in the email (or too many)
    Foo2 ->> Foo1 : Request not accepted
end
end
@enduml
