@startuml
title Диаграмма последовательности Psec
autonumber
actor "Сотрудник ИБ" as Foo
box "Mail Server"
participant "Почтовый ящик\nадминистратора сети" as Foo1
participant "Почтовый ящик\nPsec" as Foo2
end box
participant "Psec Server" as Foo3
participant "Log Server" as Foo4
participant "Коммутатор\nдоступа" as Foo5
actor "Системный\nадминистратор" as Foo6
Foo -> Foo1 : Сообщение с заявкой на\nподключение нового устройства
Foo1 -> Foo2 : Форвардинг сообщения\nс заявкой
loop Проверка на наличие входящих сообщений (два раза в минуту)
    Foo3 <-[#red]> Foo2 : POP3
alt Проверка сообщения
    Foo3 -> Foo3 : Создание дочернего процесса\nдля выполнение одной заявки
    note left
     Трек-идентификатор
     заявки содержит
     MAC-адрес устройства
    end note
    Foo3 <-[#red]> Foo2 : SMTP
    Foo2 ->> Foo1 : Заявка принята в обработку
    note left
     "<<MAC-адрес устройства>>
     принят в обработку"
     в теме сообщения
    end note
    == Выполнение одной заявки ==
    loop Запрос к БД лог-сервера (раз в минуту)
        Foo3 <-[#blue]> Foo4 : SSH подключение к лог-серверу,\nзапрос к БД Syslog (netmiko)
        note left
         Запрос содержит MAC-адрес
         нового подключаемого устройства
        end note
        hnote over Foo3, Foo4 : Ожидание подключения устройства
        ...
        Foo6 -> Foo5 : Подключение\nнового устройства
        Foo5 ->> Foo4 : Syslog сообщение
        note right
         Сообщение
         информационной безопастности
        end note
        Foo4 --> Foo3 : Ответ от БД лог-сервера
        Foo3 -> Foo3 : Парсинг syslog сообщения
        note left
         Для дальнейшей настройки необходимы
         ip-адрес коммутатора доступа,
         порт к которому подключено новое устройство
        end note
        Foo3 <-[#blue]> Foo5 : SSH подключение к коммутатору доступа,\nвыполнение насторек (netmiko)
        Foo3 <-[#red]> Foo2 : SMTP
        alt #LightBlue Сообщение с результатом выполнения
            Foo2 ->> Foo1 : Заявка выполнена
            note right
             Статус выполнения заявки
             в теме сообщения,
             лог выполнения
             заявки в теле сообщения
            end note
        autonumber 14.1
        else #LightBlue Настройки выполнены ранее
            Foo2 ->> Foo1 : Заявка выполнена
        else #Pink Устройство в списке исключенных
            Foo2 ->> Foo1 : Заявка не выполнена
        else #Pink Попытка подключения устройства через Hub
            Foo2 ->> Foo1 : Заявка не выполнена
        else #Pink Порт доступа в состоянии shutdown
            Foo2 ->> Foo1 : Заявка не выполнена
        else #Pink Не удалось настроить
            Foo2 ->> Foo1 : Заявка не выполнена
        end
        autonumber 7.1
        break #Pink Окончание рабочего дня (после 18:00)
            Foo2 ->> Foo1 : Заявка не выполнена
            note right
             Устройство не было подключено
             в течение дня
            end note
        end
    end
autonumber 6.1
else #Pink Заявка поступила не от сотрудника ИБ
    Foo2 ->> Foo1 : Заявка не принята в обработку
else #Pink В теле письма отсутствует MAC-адрес (либо их слишком много)
    Foo2 ->> Foo1 : Заявка не принята в обработку
end
end
@enduml

